version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "flask run --host 0.0.0.0 --port 5001 --reload"
    ports:
      - '5001:5001'
    volumes:
      - .:/app
