version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "flask run --host 0.0.0.0 --port 5001 --reload"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app5001.rule=Host(` thattalaw.duckdns.org`)"
      - "traefik.http.routers.app5001.entrypoints=web"
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
    networks:
      - web

  redis:
    image: redis:latest
    ports:
      - '6379:6379'

networks:
  web:
    external: true
